#+title:
#+author:
#+date:
#+options: toc:nil
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \definecolor{string}{rgb}{0,0.6,0} \definecolor{shadow}{rgb}{0.5,0.5,0.5} \definecolor{keyword}{rgb}{0.58,0,0.82} \definecolor{identifier}{rgb}{0,0,0.7}
#+LATEX_HEADER: \renewcommand{\ttdefault}{pcr} \lstset{basicstyle=\ttfamily\small\bfseries, frame=shadowbox, showstringspaces=false, rulesepcolor=\color{shadow}, keywordstyle=\color{keyword}, stringstyle=\color{string}, identifierstyle=\color{identifier}, commentstyle=\mdseries\textit, inputencoding=utf8, extendedchars=true, breaklines=true, breakatwhitespace=true, breakautoindent=true, numbers=left, numberstyle=\ttfamily\footnotesize\textit, framexleftmargin=7mm}
#+LATEX_HEADER: \hypersetup{unicode=true, pdftex=true,plainpages=false,colorlinks=true,linkcolor=black,anchorcolor=black,citecolor=black,filecolor=black,menucolor=black,runcolor=black,urlcolor=black}
#+LATEX_HEADER: \lstset{ extendedchars=true, literate={á}{{\'a}}1 {é}{{\~e}}1 {í}{{\'i}}1 {ó}{{\'o}}1 {ú}{{\'u}}1 {ñ}{{\~n}}1 {Á}{{\'A}}1 {É}{{\~E}}1 {Í}{{\'I}}1 {Ó}{{\'O}}1 {Ú}{{\'U}}1 {Ñ}{{\~N}}1 {¡}{{!`}}1 {¿}{{?`}}1 }
#+latex: \pagestyle{empty}

Todos los usuarios de equipos de cómputo (esto es, prácticamente
cualquier persona del mundo) tienen contacto con un sistema operativo,
y ciertas expectativas acerca de su funcionamiento. ¿Cómo es que un
sistema operativo puede gestionar y compartir los recursos de cómputo?

Hoy en día, a pesar de que menos de una decena es conocida por la
población en general, hay cientos de sistemas operativos en uso y bajo
un desarrollo activo. Cada uno de ellos persigue distintos fines, sea
por la arquitectura o la capacidad de los equipos en que se ejecutará,
características específicas que implementa, o persigue atraer un
segmento distinto de la población. Todos ellos, sin embargo, realizan
las mismas operaciones básicas, parten de los mismos fundamentos.

Este libro, diseñado para servir como bibliografía para un curso de
Sistemas Operativos para licenciatura, presenta las principales áreas
en que se divide el trabajo de un sistema operativo.

El libro está escrito nativamente en español, salvando las
inconveniencias en que muchas veces incurren las traducciones
técnicas. Los autores (uno mexicano, dos argentinos y uno colombiano)
procuraron que el lenguaje y los términos empleados resulten lo más
neutros y universales a la región latinoamericana.

\vskip 1em \hrule \vskip 1em

Este libro fue escrito con el apoyo de la Iniciativa Latinoamericana
de Libros de Texto Abiertos «LATIn» (http://latinproject.org/), por lo
que se permite su libre redistribución y modificación bajo los
términos de la licencia Creative Commons Reconocimiento-CompartirIgual
(CC BY-SA) versión 4.0. La última versión del libro está disponible en
línea, en http://sistop.org/

