#+title: Ejemplos de lineamientos empleados por otros docentes

* A. Leonardo Bañuelos Saucedo

http://dcb.fi-c.unam.mx/users/angellbs/

** Desarrollo en clase

- La clase se desarrollará en un ambiente de respeto y cordialidad,
  principalmente entre los compañeros del grupo.
- La asistencia no es obligatoria; sin embargo, los ejercicios de
  clase se contabilizan como tareas y participaciones.
- Algunos ejercicios son resueltos por los alumnos en el pizarrón. El
  alumno puede ser voluntario o seleccionado por el profesor.
- No se tolerará la descortesía.
- Los teléfonos celulares deberán apagarse o ponerse en modo
  silencioso. No se permiten llamadas telefónicas, mensajes de texto
  ni grabaciones.
- No hay hora límite para llegar a la clase, pero si se llega tarde,
  deberá ingresar en silencio y entregar la tarea inmediatamente.

** Exámenes Parciales
- Se realizan un mínimo de 3 exámenes parciales.
- Se aplican mini exámenes, para observar los avances parciales por
  subtemas.
- Hay exámenes sorpresa.
- No se permite ningún tipo de fraude en los exámenes.
- No se debe utilizar tinta de color rojo en los exámenes.

** Evaluación
- Las tareas se entregan al inicio de la clase, durante los primeros 15 minutos. No se reciben tareas atrasadas.
- Los trabajos que se soliciten deberán presentarse en limpio, con bibliografía. La calificación del trabajo estará basada en su contenido, la defensa desarrollada por el alumno y la presentación. La defensa se refiere al nivel de conocimientos sobre el trabajo que demuestre tener el alumno, esto es, se preguntará sobre el trabajo al momento de la entrega o en la clase siguiente.
- En las preguntas del examen se califica el procedimiento y el resultado.
- Salvo que se indique lo contrario, cada pregunta o reactivo se califica sobre 10 puntos y posteriormente se obtiene el promedio.
- En los exámenes no se permite el uso de teléfonos celulares, ni de ningún otro tipo de dispositivos de comunicación.
- La calificación del curso se obtiene mediante un promedio ponderado de tareas, series y exámenes. Ver porcentajes según la asignatura.
- La calificación mínima para exentar depende de la asignatura.
- Los alumnos que no exenten deberán presentar el examen ordinario (final). Ver el Reglamento General de Exámenes.
- Si se deja un proyecto final, éste representará el 20% de la calificación final

** Particularidades por Asignatura

*** Probabilidad y Estadística
- Se aplicarán exámenes parciales de recuperación. Pueden presentarse
  todos los exámenes parciales de recuperación que se deseen, siempre
  que no se obtenga una calificación menor que la registrada
  anteriormente y mientras no se haya aplicado el siguiente examen
  parcial. Los exámenes de recuperación se aplican por las tardes,
  previo acuerdo y disponibilidad.
- Exentos con 8
- Porcentajes:
  - Tareas :: 15%
  - Series :: 15%
  - Exámenes :: 70%

*** Investigación de Operaciones II
- Exentos con 6.
- Porcentajes:
  - Tareas :: 20%
  - Prácticas y exposición :: 15%
  - Exámenes :: 65%.


* Erik Castañeda De Isla Puga

http://dcb.fi-c.unam.mx/users/erikcip/principal.htm

** Evaluación del curso de Ecuaciones Diferenciales, Grupo 10 del semestre 2013-1
El estudiante irá formando su calificación del semestre (C.S) de la siguiente
manera:


#+begin_center
C.S . = 0.8 ( C.E.) + 0.2 ( C.T .) + T .O.
#+end_center

donde:

- C.S. :: Calificación del semestre,
- C.E. :: Calificación de exámenes,
- C.T. :: Calificación de tareas,
- T.O. :: Trabajo opcional.

La calificación de exámenes (C.E.) se obtendrá:
#+begin_center
C.E. = 0.7 ( E.P.) + 0.3 ( E.C.)
#+end_center

donde:
- E.P. :: Calificación promedio de los exámenes parciales cuyas fechas
          se fijarán con anticipación durante las clases. Estos
          exámenes serán de larga duración y evaluarán uno o dos
          temas.
- E.C. :: Calificación promedio de los exámenes complementarios que
          serán de breve duración, entre veinte y veinticinco minutos
          al final de alguna clase. No serán sorpresa ni en su
          contenido temático ni en el día de su aplicación. Serán
          anunciados una o dos clases antes, así como el tema por
          evaluar.

Las tareas se plantearán durante las clases. No es obligatorio
resolver las series que se presentan en la página del Departamento de
Ecuaciones Diferenciales aunque se recomienda consultarlas. Las únicas
tareas obligatorias serán las solicitadas en clase. Las tareas deben
entregarse antes de sentarse. Deben depositarse encima del escritorio
del profesor. No se recibirán tareas atrasadas y si un alumno se
sienta primero y después quiere entregar su tarea ya será atrasada y
no se aceptará.

El trabajo opcional es de investigación y su objetivo es que el
estudiante conozca y se aproxime a su carrera. El título del trabajo
debe ser:

/“La importancia de las ecuaciones diferenciales en la carrera ...”/

Como puede observarse, en la parte final del título del trabajo debe
escribirse la carrera que el estudiante está cursando. El trabajo no
es una lista de aplicaciones, aunque dentro de la investigación pueden
describirse algunas.  El trabajo puede elaborarse en forma individual
o en equipo. Los equipos deben tener hasta cinco integrantes como
máximo y deben estar cursando la misma carrera o carreras afines.

Los límites máximo y mínimo de contenido son libres; es decir, no hay
un número fijo de hojas, si es que se decide hacerlo por escrito. La
forma de entrega del trabajo también es libre. Puede ser, como se
dijo, escrito, pero puede entregarse en un CD, en una memoria USB, o
como sea la decisión de quien entrega el trabajo. La investigación
también es libre. Puede consultarse bibliografía, ingenieros de la
especialidad, profesores, estudiantes avanzados, información en la
red, etc. Será motivo de muy baja calificación la práctica de
“copiar-pegar” (“copy-paste”)

La fecha límite de entrega del trabajo será el viernes 16 de noviembre
a la hora de clase. No habrá prórrogas.

El valor T.O. del trabajo que se sumará en C.S. se determinará de
acuerdo con la tabla:

#+begin_center
| Calificación | T.O. |
|--------------+------|
|           10 |  1.0 |
|            9 |  0.8 |
|            8 |  0.6 |
|            7 |  0.4 |
|            6 |  0.2 |
#+end_center

La asistencia a clase es obligatoria. Al final del semestre el
estudiante debe tener como mínimo el 80 % de asistencias. Con un
porcentaje menor no se tendrá derecho a examen final o a quedar
exento.

Para que un estudiante pueda exentar el examen final, debe cumplir con:

1. C.S . ≥ 7.0
2. Haber reprobado cuando mucho un examen parcial.

No se guardan calificaciones.

Quienes presenten examen final, en el primer ordinario se considerará
el promedio de la calificación del primer examen ordinario y la
calificación del semestre (C.S.)

En el segundo examen se tomará en cuenta exclusivamente la
calificación del segundo examen ordinario; es decir, ya no contará la
calificación del semestre (C.S.)


* Francisco José Castillo Cortés

http://dcb.fi-c.unam.mx/users/franciscojcc/

Cálculo diferencial

** Evaluación de la asignatura

La calificación del curso (C. C.)se hará de la siguiente manera:

- Tres exámenes complementarios tal que el promedio de ellos será
  considerado como un examen parcial.
- Tres exámenes parciales más el promedio de los complementarios. Peso
  de exámenes parciales 60%.
- Tareas y trabajos de investigación, para entregar, 30%
- Examen sorpresa 10%

Los exámenes serán en las siguientes fechas:

- Primer examen complementario :: 31 de agosto de 2011
- Segundo examen complementario :: 5 de octubre de 2011
- Tercer examen complementario :: 9 de noviembre de 2011
- Primer examen parcial :: 14 de septiembre de 2011
- Segundo examen parcial :: 19 de octubre de 2011
- Tercer examen parcial :: 23 de noviembre de 2011

En caso de que en el primer examen parcial y/o también en el segundo
examen parcial se tengan al menos tres faltas de ortografía, la
calificación en el examen en que se comenta tal hecho será cero.

La calificación mínima aprobatoria es 60

Lineamientos:

Para quedar exento de examen final, la calificación del curso deberá
ser igual o mayor a 80.

De no quedar exento, de este camino, también quedan con calificación
definitiva reprobatoria quienes no alcancen una calificación del curso
mayor a 30 (treinta) puntos.

Al presentar examen final (primero y/o segundo), se calculará un
promedio de la siguiente manera:

$Promedio = {{CC + 2(final)}\over{3}}$

esto es, la calificación del curso más el doble de lo obtenido en
cualquiera de los finales, se dividirá entre tres. PARA QUE SE CALCULE
EL PROMEDIO, LA CALIFICACIÓN EN EL FINAL DEBE SER APROBATORIA (mayor o
igual a seis).

De existir fraude (como copiar en cualquiera de los exámenes) todos
los involucrados perderán su oportunidad de exentar la asignatura y
además se alterará la forma en que se les promediará su calificación
de la siguiente manera.

$Promedio = {{CC + 2(final)}\over{4}}$

Asignación de calificación final (EN ACTAS):

|----------------+----|
| C.F. ≥ 95      | 10 |
|----------------+----|
| 85 ≤ C.F. < 95 |  9 |
|----------------+----|
| 75 ≤ C.F. < 85 |  8 |
|----------------+----|
| 65 ≤ C.F. < 75 |  7 |
|----------------+----|
| 60 ≤ C.F. < 65 |  6 |
|----------------+----|
| 0 ≤ C.F. < 60  |  5 |
|----------------+----|

Una vez aprobado el curso por exención o ya por haber aprobado el primer final, se podrá tomar en cuenta un proyecto final realizable de manera voluntaria que se deberá entregar a más tardar el 23 de noviembre de 2011. Presentar el segundo final, anula el haber presentado proyecto.

** Proyecto final.

*** Lineamientos del Proyecto.

1. Se podrá entregar desde la segunda semana de clases, en el cubículo
   del profesor y hasta el 23 de noviembre de 2011.
2. Se podrá realizar una de entre varias opciones como son:
  1. Concurso Madame Curie en el que se tomarán los lineamientos
     adicionales del concurso y no es necesario que todos los
     participantes del concurso estén inscritos en el grupo de cálculo
     diferencial del presente semestre. Al profesor se le entregará
     únicamente una copia del trabajo escrito.
  2. Un trabajo de investigación totalmente escrito en el que se
     aborde un tema de la asignatura o se desarrolle un problema o se
     menciones un uso de alguno de los temas de la asignatura. No hay
     mínimo ni máximo en cuanto a hojas escritas y es estrictamente
     INDIVIDUAL.
  3. Desarrollar un modelo físico en el que se utilice alguno de los
     temas de la asignatura incluyendo un trabajo escrito en el que se
     explique la forma en que apoya al modelo físico. Podrá ser en
     equipo máximo de dos personas.
  4. Una idea distinta podría ser planteada al profesor y junto con
     él, se acordará su viabilidad.
3. Si el proyecto está completo y correcto, se adicionarán diez puntos
   a la calificación del alumno.
4. Debe quedar claro que son los diez puntos o ninguno, esto es, no
   hay términos medios, está bien el proyecto o cualquier otra opción,
   está mal.
5. De existir alguna situación no considerada, el profesor tendrá la
   última palabra.
