#+TITLE: Sistemas Operativos
#+AUTHOR: Gunnar Wolf
#+EMAIL: gwolf@gwolf.org

* Generalidades del curso
** Calendario general
Esta materia se imparte los días /lunes, miércoles y viernes/ de
13:00 a 14:30 en *algún día sabré qué salón*.

Según el [[https://www.dgae.unam.mx/pdfs/semestral2013.pdf][calendario del plan semestral 2013]], la primer sesión es el
lunes 28 de enero, y la última el viernes 24 de mayo, lo cual nos
daría 16 semanas (ya descontando el asueto académico por Semana Santa)
— 48 clases, o las 72 horas que contempla el [[http://www.ingenieria.unam.mx/paginas/Carreras/planes2010/Computacion/05/sistemas_operativos.pdf][temario de la materia]].

Por feriados, /perderemos/ cinco sesiones: 4 de febrero, 18 de marzo,
y 1, 10 y 15 de mayo. Esto es, para el semestre 2013-2, en este curso
contaremos con 64.5 horas efectivas de clase.

** Punto de partida

Esta clase asume que tienen todo el conocimiento básico de los
[[http://www.ingenieria.unam.mx/paginas/Carreras/planes2010/ingComputo_Plan.htm][primeros cuatro semestres de la carrera de Ingeniería en
Computación]]. Esto es, aunque la única seriación formal es con la
materia /Estructura y programación de computadoras/, voy a dar por
hecho familiaridad con los demás conocimientos, en particular con
[[http://www.ingenieria.unam.mx/paginas/Carreras/planes2010/Computacion/02/computacion_para_ingenieros.pdf][Computación para ingenieros]], [[http://www.ingenieria.unam.mx/paginas/Carreras/planes2010/Computacion/03/programacion_avanzada_y_metodos_numericos.pdf][Programación avanzada y métodos
numéricos]], [[http://www.ingenieria.unam.mx/paginas/Carreras/planes2010/Computacion/04/algoritmos_y_estructuras_de_datos.pdf][Algoritmos y estructuras de datos]].

Asumo también que están familiarizados (o que se familiarizarán
prontamente al iniciar el curso) con algún lenguaje de programación
de alto nivel, y –al menos a nivel básico– con C — En ambos casos,
no sólo para desarrollar ejercicios, sino para entender código
ejemplo.

Resultará muy conveniente que tengan acceso a una computadora con
sistema operativo Linux

** Forma de evaluación


* Introducción a los sistemas operativos
- Objetivo :: El alumno describirá las funciones, características y
              estructura de los sistemas operativos
** Funciones y objetivos de los sistemas operativos
** Evolución de los sistemas operativos
** Estructuras de los sistemas operativos
* Administración de procesos
- Objetivo :: El alumno identificará los tipos de procesos y sus
	      estados. Describirá las diferentes técnicas de
	      comunicación y sincronización de procesos concurrentes.
** Procesos. Concepto y estados de un proceso
** Hilos y multihilos
** Concurrencia
*** Exclusión mutua y sincronización
*** Bloqueos mutuos
* Administración de memoria
- Objetivo :: El alumno explicará las diferentes técnicas de
              asignación de memoria contigua y no contigua.
** Funciones y operaciones del administrador de memoria
** Asignación de memoria contigua
*** Partición de la memoria
*** Paginación
*** Segmentación
** Memoria virtual
*** Concepto
*** Paginación
*** Segmentación
*** Paginación y segmentación combinadas
*** Reemplazo de páginas
*** Asignación de marcos e hiperpaginación
* Planificación de procesos
- Objetivo :: El alumno explicará las diferentes técnicas de
              asignación del procesador a los procesos.
** Tipos de planificación
** Algoritmos de planificación
** Planificación de multiprocesadores y en tiempo real
** Planificación de hilos
* Sistemas de archivos
- Objetivo :: El alumno describirá las diferentes formas de
	      organización y acceso a archivos, basándose en el modelo
	      de sistema de archivos.
** Concepto y tipos de archivos
** Organización y acceso a archivos
** Estructura de los directorios
** Estructura de los sistemas de archivos
** Métodos de asignación
** Administración del espacio libre
* Sistemas de entrada/salida
- Objetivo :: El alumno explicará las diversas funciones de
	      entrada/salida en la administración y control de
	      dispositivos periféricos. Además analizará, con un
	      enfoque práctico, las diferentes políticas y técnicas de
	      almacenamiento de archivos en disco.
** Dispositivos de entrada/salida
** Organización de las funciones de entrada/salida
** Almacenamiento intermedio de la entrada/salida
** Planificación de discos
* Sistemas distribuidos
- Objetivo :: El alumno explicará cómo se administran los procesos y
	      archivos que se encuentran en un sistema distribuido.
** Proceso cliente/servidor
** Paso distribuido de mensajes
** Llamadas a procedimiento remoto
** Agrupaciones
** Gestión distribuida de procesos
*** Migración de procesos
*** Estados globales distribuidos
*** Exclusión mutua distribuida
*** Bloqueo mutuo distribuido
** Sistema de archivos distribuidos
* Seguridad y medidas de desempeño
- Objetivo :: El alumno explicará cómo asegurar el adecuado
              funcionamiento del sistema operativo.
** Amenazas a la seguridad
** Protección
** Intrusos
** Software maligno
** Desempeño, coprocesadores, risc y flujo de datos
** Modelado analítico
* Bibliografía
** Del programa de la Facultad
- CARRETO DE MIGUEL, GARCÍA PÉREZ: /Sistemas Operativos. Una visión
  aplicada/ (España, Mc. Graw Hill/Interamericana de España, 2001)
- DEITEL, H. M.: /Introducción a los Sistemas Operativos/ 2a. edición
  (México Addison Wesley Iberoamericana, 2000)
- FLYNN, Ida y McIver A.: /Sistemas Operativos/ 3a. edición (México,
  Thomson Learning, 2001)
- SILBERSCHATZ, GALVIN, GAGNE: /Sistemas Operativos/ 6a. edición
  (México, Limusa - Wiley, 2002)
- STALLINGS, William: /Operating Systems/ 5th edition (USA, Prentice
  Hall, 2004)
- TANENBAUM, Andrew y WOODHULL, Albert: /Sistemas Operativos. Diseño e
  implementación/ 2a. edición (México, Prentice Hall, 1999)
- MÁRQUEZ GARCÍA, Francisco Manuel: /UNIX. Programación avanzada/
  3a. edición (México Alfa omega Grupo Editor, 2004)

** Adicional
