#+title: Tarea: Sincronización
#+date: 5-10 de septiembre

Implementa hilos que controlen el siguiente sistema:

 - La cochera de casa es de portón de apertura automática
 - Una vez que la puerta comienza a abrir, tarda x tiempo en quedar
   abierta
 - Una vez que la puerta comienza a cerrar, tarda x tiempo en quedar
   cerrada
 - El coche toma cierto tiempo en entrar y salir. Particularmente si
   hay peatones o vehículos cruzando frente a la puerta, tienes que
   esperar a que terminen de pasar.
 - La batería del control está muy débil, por lo que cuando llegas
   tienes que pedirle a otro actor que abra y cierre por tí. Cuando te
   vas también necesitas esta ayuda.
 - Si el coche es golpeado por la puerta, se abolla y hay que llevarlo
   al taller. No quieres que eso ocurra.

Implementa un sistema que tome en cuenta las restricciones en cuestión. Para su calificación, importa que:

 - El problema se resuelva correctamente
 - El tiempo de espera sea razonable
 - El código sea válido y legal en tu lenguaje favorito
   - Puedes asumir que la semántica del control de hilos, señales y
     primitivas de sincronización es similar a la expuesta en clase,
     no hace falta implementar eso a detalle.

Puedes enviar tu código más de una vez si sientes que lo mejoras; el
que vale es el último.

Esta tarea pueden hacerla individualmente o en equipos de dos
personas; en caso de que elijan hacerlo así, les pido que /ambos/
suban el mismo archivo, y que /ambos/ indiquen quiénes son los
autores.

La tarea debe ser enviada a la hora de inicio de la próxima clase
(martes 10 de septiembre). Recuerda que, si no la enviaste a tiempo,
puedes enviar tu tarea todavía por una semana más, con un máximo del
80% de calificación.
