#+TITLE: Examen parcial 3: Sistemas de archivos
#+AUTHOR: Sistemas Operativos (Grupo 1 – Gunnar Wolf)
#+DATE: 2013-05-17
#+OPTIONS: num:t toc:nil
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LANGUAGE: es

1. Describe dos mecanismos por medio de los cuales el sistema de
   archivos puede identificar de qué tipo es determinado archivo.

2. Hay diferentes modos en que un programa puede accesar a la
   información contenida en un archivo; los principales modos que
   vimos en clase son /secuencial/, /aleatorio/ y /relativo a
   índice/. Indica qué casos de uso resuelve mejor cada uno de estos
   modos de acceso.

3. De las siguientes afirmaciones, indica cuáles se refieren a /ligas
   duras/ (D), cuáles a /ligas simbólicas/ (S), y cuáles a /enlaces
   directos/ (E). Hay una sóla respuesta correcta para cada
   afirmación.
   1. Son dos (o más) entradas en el directorio apuntando al mismo
      i-nodo
   2. Es un archivo normal e independiente en el sistema de archivos,
      que podría ser abierto directamente por los programas
   3. Pueden apuntar a directorios, incluso creando ciclos
   4. Su tipo de archivo en el directorio está indicado por la
      extensión =.LNK=
   5. El sistema operativo /resuelve directamente/ todas las
      operaciones /como si fueran/ al archivo referido
   6. No pueden referirse a archivos en sistemas de archivos distintos
      del propio
   7. Pueden existir en un sistema de archivos tipo FAT
   8. Si un usuario elimina cualquiera de las referencias a un archivo
      empleando este esquema, el archivo sigue existiendo en las demás

4. Describe el funcionamiento de un /sistema de archivos con bitácora/
   (/journaling file system/). ¿Cómo nos asegura que el sistema se
   mantendrá consistente después de una interrupción abrupta?

5. Presentamos algunos algoritmos para gestionar las solicitudes de
   acceso a disco — /Primero llegado, primero servido/ (FIFO), /Tiempo
   más corto a continuación/ (SSTF), /Elevador/ (SCAN), y algunas de
   sus variaciones. Mencionamos también que, a pesar de la importancia
   de conocerlos por su importancia histórica, hoy en día han dejado
   de ser tan importantes como lo fueron hacia los 1980. Menciona dos
   factores que han llevado a que pierdan relevancia.

-----

#+BEGIN_CENTER
*Información importante*
#+END_CENTER
Estamos ya en la recta final del semestre; van aquí las indicaciones
para los exámenes finales.
- ¡Espero que califiques para la exención! Recuerda: 80% de
  asistencias (máximo de 8 faltas), calificación global de 8.
- ¿Presentas examen final? Tienen derecho a presentar examen en 1ª
  vuelta todos los que tengan el 80% de asistencias
  - Para el examen 1ª vuelta (*29 de mayo, 13:00, A107*), la
    presentación del trabajo final cuenta (como en el curso completo)
    hasta un 20% de la calificación.
    - La máxima calificación alcanzable con el examen final y /sin/ el
      trabajo es de 9
    - Entregar un buen trabajo te da el /colchón/ de poder alcanzar el
      110%
  - Para el examen 2ª vuelta (*7 de junio, 13:00, A107*), el examen
    vale 100%, y no cuenta /nada más/ que el examen. /Todos los
    alumnos del curso/ pueden presentar 2ª vuelta, independientemente
    de sus asistencias.
