#+TITLE: Examen parcial, primera vuelta
#+AUTHOR: Sistemas Operativos (Grupo 1 – Gunnar Wolf)
#+DATE: 2013-05-29
#+OPTIONS: num:t toc:nil
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LANGUAGE: es

Tienes hasta dos horas para responder este examen.

Recuerda que, en esta primera vuelta, el examen vale el 90% de la
calificación final, y el trabajo final un 20% adicional, para un
máximo teórico de 110%. El trabajo final /debe ya haber sido
entregado/ al momento de iniciarse el examen.

-----

1. Relaciona cada concepto con su descripción: ¿Cuáles son las
   principales características de los distintos modelos de
   multiprocesamiento? a) Cómputo en la nube; b) NUMA; c) SMP; d)
   Cluster o cúmulo; e) Grid o malla
   - Modelo de distribución del cómputo en que se pueden proveer (como
     un servicio) recursos de cómputo para necesidades específicas
     sobre demanda, bajo tres modalidades principales: /IaaS/, /PaaS/
     y /SaaS/
   - Cada procesador /está cerca/ de ciertos bancos de memoria,
     aunque puede también direccionar a los que le quedan más lejos.
   - Computadoras independientes, con características idénticas o
     muy similares de hardware, conectadas a través de una red
     local (LAN)
   - Computadoras independientes, posiblemente con características
     de hardware muy distintas entre sí, conectadas típicamente por
     redes de área amplia (WAN) como Internet
   - Todos los procesadores tienen el mismo acceso a la memoria y
     los dispositivos del sistema

2. Vimos varios patrones de sincronización que emplean a los semáforos
   como mecanismo de comunicación. Menciona y describe brevemente a
   tres de estos patrones.

3. Asumiendo los siguientes procesos, presenta la representación
   gráfica de cómo el despachador les asignaría el CPU, y la tabla de
   análisis, bajo un esquema de ronda (/round-robin/) con $q=4$
   | Proceso | Llegada | $t$ |
   |---------+---------+-----|
   | A       |       0 |   7 |
   | B       |       3 |  10 |
   | C       |       5 |   2 |
   | D       |      16 |   6 |
   | E       |      20 |   5 |
   | F       |      20 |   3 |

4. Elabora un esquema de cómo se estructura la información sobre
   varios discos bajo RAID niveles 0, 1 y 5. Para cada uno de estos
   niveles, indica el impacto que su empleo tendría en cuanto a
   espacio total, velocidad de acceso y confiabilidad.

5. Describe brevemente a la /emulación/, /virtualización asistida por
   hardware/ y /paravirtualización/. Para cada una, presenta por lo
   menos un caso en que convenga su utilización. ¿Hay alguno de estos
   esquemas que emplees regularmente?
