#+TITLE: Temas sugeridos a desarrollar para exposición
#+AUTHOR: Gunnar Wolf
#+EMAIL: sistop@gwolf.org
#+options: toc:nil
#+STYLE: <link rel="stylesheet" type="text/css" href="css/sistop.css" />

Parte de la calificación del curso será determinado por una exposición
que pueden realizar, de forma individual o en equipos de hasta tres
personas. Aquí iré presentando algunos temas que pueden resultar de su
interés.

Además de exponer el tema, les pido que me entreguen un reporte
escrito al respecto, tocando los puntos principales y detallando sus
fuentes de información.  Obviamente, se espera que un equipo más
grande haga un trabajo de mayor profundidad, y serán calificados más
rigurosamente.

Si hay algún tema que vean relacionado temáticamente con el tema que
estemos estudiando, por favor no duden en comentármelo para que le
encontremos en conjunto un ángulo adecuado para presentarlo.

Intentaremos que los temas vayan siendo presentados junto con la clase
en cuestión, para no romper el hilo temático del grupo.

* Introducción a los sistemas operativos
* Relación con el hardware: Estructuras y funciones básicas
- /Rootkits: Escondiéndose del administrador/

  Complementando a la división de espacio usuario y espacio kernel,
- /Sistemas basados en grid/
* Administración de procesos
* Administración de memoria
* Planificación de procesos
* Sistemas de archivos
