#+SETUPFILE: ../setup_notas.org
#+TITLE: Presentación

#+latex: \section*{Acerca del libro}
#+html: <h2>Acerca del libro</h2>

Este libro busca brindar a estudiantes y docentes de las carreras de
/Ingeniería en Computación/, /Informática/, /Ciencias de la
Computación/ y similares un material completo, general y autocontenido
sobre la materia de /Sistemas Operativos/. No se asume conocimiento
previo sobre la temática, aunque se utilizarán conceptos de
estructuras de datos y algoritmos básicos.

#+latex: \section*{Justificación}
#+html: <h2>Justificación</h2>

Actualmente existe vasta bibliografía sobre Sistemas Operativos, sin
embargo la gran mayoría está escrita en inglés, y cuando estan
disponibles en castellano, su traducción deja mucho que desear,
llevando a conceptos confusos y difíciles de comprender. La intención
de los autores es que el presente texto provea un material redactado
originalmente en castellano, revisado por docentes latinoamericanos
utilizando la terminología más adecuada para los alumnos de la región
y eliminando muchos de los errores de traducción.

Generalmente el material de cursos de Sistemas Operativos está
compuesto por partes de distintos libros, artículos de investigación,
recursos en linea, software, ejercitación, etc. Por ello, el alumno
debe recurrir a distintas fuentes durante el curso. La presente
propuesta pretende ser de utilidad tanto para alumnos como para
docentes como una única publicación autocontenida. Cabe remarcar
también que el material bibliográfico generalmente está protegido por
derecho de autor, es costoso y en muchos casos de dificil acceso
(sobre todo las publicaciones en inglés).

Los contenidos de la bibliografía clásica de Sistemas Operativos están
basadas en re-ediciones y compendio de libros de hace varias décadas
que incluyen temas obsoletos o desactualizados. Existen también
desarrollos y tendencias nuevas en el área que aun no han sido
integradas en la bibliografía clásica, y mucho menos a las
traducciones. Nuestra propuesta pretende también revisar y actualizar
los conceptos clásicos de sistemas operativos inlcuyendo material de
publicación reciente.

El libro se desarrolló dentro del marco del [[http://www.latinproject.org][Proyecto LATIn]], enfocado a
la creación de libros de texto con un esquema de licenciamiento libre,
derivados de la creación y colaboración de grupos de trabajo
multinacionales, para la región latinoamericana.

#+latex: \section*{Estructura temática}
#+html: <h2>Estructura temática</h2>

El texto comprende los siguientes capítulos:

- 1. Introducción :: Para comenzar a hablar de sistemas operativos, es
                  necesario en primer término enmarcar /qué es/ un
                  sistema operativo y cuáles son sus funciones
                  principales. También es importante detallar algunos
                  puntos que, contrario a la percepción común, /no
                  pueden/ considerarse parte de sus funciones.

		  Este tema se presenta apoyado de la evolución
                  histórica del cómputo, haciendo énfasis en por qué
                  este proceso evolutivo en particular desembocó en
                  los sistemas operativos que existen hoy en día.

- 2. Relación con el hardware :: Partiendo de que una de las
     principales tareas del sistema operativo es presentar una
     /abstracción regular/ del hardware a los procesos que se
     ejecuten, resulta importante presentar cómo éste está
     estructurado, y cómo el sistema operativo puede comunicarse con
     él.

     En este capítulo abordan la /jerarquía de almacenamiento/, el
     mecanismo de /interrupciones/ y /excepciones/ y el papel que
     juegan para las /llamadas al sistema/, las características base
     de diversos tipos de dispositivo del sistema, el concepto de
     /canales/ (o /buses/) de comunicación, el mecanismo de /acceso
     directo a memoria/, y una introducción al que puede ser visto
     como tema conductor a lo largo de todo el libro: La importancia
     y complejidad de la /concurrencia/, y su relación con el
     /paralelismo/ y /multiprocesamiento/.

- 3. Administración de procesos ::
- 4. Planificación de procesos ::
- 5. Administración de memoria ::
- 6. Organización de archivos ::
- 7. Sistemas de archivos ::

Los siguientes temas resultan muy importantes para la comprensión y
para el desarrollo futuro de la materia, pero dado que son /empleados/
por el sistema operativo (y no necesariamente son /parte integral/ del
mismo), se presentan como apéndices

- A. Software libre y licenciamiento ::
- B. Virtualización ::
- C. El medio físico y el almacenamiento ::

#+latex: \section*{Licenciamiento}
#+html: <h2>Licenciamiento</h2>
