#+SETUPFILE: ../setup_notas.org
#+TITLE: Sistemas Operativos — Sistemas de entrada/salida

* Ideas a desarrollar

Estas secciones son copiadas de otras áreas del curso, a donde no
pertenecían tan claramente. Hay que darle estructura.

** Archivos de dispositivo

Unix introdujo el concepto de que /todo es un archivo/: En el sistema
Unix original, todos los dispositivos podían ser controlados a través
de un /archivo especial/ que, en vez de almacenar información, apunta
a estructuras en el sistema que controlan a cada dispositivo. Este
concepto sobrevive en los sistemas derivados de Unix al día de hoy,
aunque varias clases de dispositivo rompen esta lógica. El sistema
operativo /Plan9/ de Bell Labs hace mantiene y amplía este concepto e
introduce los /espacios de nombres mutables/, que presenta con
interfaz de archivo archivos prácticamente cualquier objeto empleado
por el sistema.

Las principales estructuras relacionadas que encontraremos en un
sistema tipo Unix son:

- Dispositivos de caracteres :: Dispositivos con los cuales la
     información es leída o escrita un caracter a la vez y se
     presentan como /streams/ (flujos) de información, ya sea
     entrante, saliente o mixta. Algunos pueden permitir operaciones
     adicionales (por ejemplo, rebobinado), pero la manipulación de la
     información se efectúa de forma secuencial.

     Ejemplos: Impresora, unidad de cinta, modem
- Dispositivos de bloques :: Dispositivos que presentan una interfaz
     de /acceso aleatorio/ y entregan o reciben la información en
     /bloques/ de tamaño predeterminado.

     El ejemplo más claro de este tipo de dispositivos es una unidad
     de disco o una de sus particiones.

*Falta*: Cómo se maneja en sistemas no-Unix, cómo se integran los
dispositivos a la jerarquía global del sistema.


* Dispositivos de entrada/salida
* Organización de las funciones de entrada/salida
* Almacenamiento intermedio de la entrada/salida
* Planificación de discos
