#+SETUPFILE: ../setup_notas.org
#+TITLE: Software libre y licenciamiento

* Software libre
# <<SL>>

Este apéndice, a diferencia del resto del libro, no se enfoca a
asuntos técnicos, sino que a un aspecto /social/: A la construcción
del conocimiento de forma colectiva, colaborativa, que ha resultado en
el movimiento del software libre.

Si bien este tema es meramente tangente al que desarrolla el libro,
los autores consideran importante incluirlo no sólo por la importancia
que el software libre ha tenido para el desarrollo y estudio de los
sistemas operativos, sino que directamente –como se explica en la
sección \ref{SL_bienes_cult_lib}– para el presente libro en
particular.

Citando [[https://www.gnu.org/philosophy/free-sw.es.html][la definición que brinda la Fundación del Software Libre (Free
Software Foundation)]], el software libre es todo programa en el cual
los usuarios tienen la libertad para /ejecutar, copiar, distribuir,
estudiar, modificar y mejorar el software/. Esto es, todo programa
cuyo modelo de licenciamiento respete las /cuatro libertades del
software/:

#+begin_quote
- La libertad de ejecutar el programa para cualquier propósito.
- La libertad de estudiar cómo funciona el programa, y cambiarlo para
  que haga lo que usted quiera. El acceso al código fuente es una
  condición necesaria para ello.
- La libertad de redistribuir copias para ayudar a su prójimo.
- La libertad de distribuir copias de sus versiones modificadas a
  terceros. Esto le permite ofrecer a toda la comunidad la oportunidad
  de beneficiarse de las modificaciones. El acceso al código fuente es
  una condición necesaria para ello.
#+end_quote

El software libre en tanto /movimiento ideológico/ tiene bien
identificados sus orígenes y génesis: 

** Algunas licencias comunes

* Bienes culturales libres
# <<SL_bienes_cult_lib>>


** La familia de licencias /Creative Commons/
# <<SL_CC>>
