#+SETUPFILE: ../setup_notas.org
#+TITLE: Acerca de los autores

- Gunnar Wolf :: De formación autodidacta, obtuvo el título de
                 licenciado en ingengeniería en software por parte de
                 la Secretaría de Educación Pública mexicana en
                 el 2011. Usuario y desarrollador de software libre,
                 es desarrollador del proyecto Debian desde el 2003.
                 ha coordinado diversos congresos nacionales e
                 internacionales relacionados con el software libre y
                 la seguridad informática.  Es técnico académico en el
                 Instituto de Investigaciones Económicas de la
                 Universidad Nacional Autónoma de México desde el
                 2005, y docente de sistemas operativos en la Facultad
                 de Ingeniería de la misma universidad desde el 2013.

- Esteban Ruiz :: Licenciado en ciencias de la computación,
                  Universidad Nacional de Rosario y técnico
                  universitario en computación. Docente desde el 2001
                  a la actualidad en materias como base de datos,
                  comunicaciones, sistemas operativos y arquitectura
                  del computador. Actualmente realiza también tareas
                  de investigación y desarrollo con software de
                  reconocimiento óptico de caracteres (*ocr*).

- Federico Bergero :: Obtuvo el título de licenciado en ciencias de la
     computación en el 2008 y de doctor en informática en el 2012
     ambos de la Universidad Nacional de Rosario,
     Argentina. Actualmente es becario posdoctoral en
     *cifasis-conicet*, y también es profesor de la Universidad
     Nacional de Rosario en el Departamento de Ciencias de la
     Computación de la *fceia*. Sus intereses incluyen sistemas de
     eventos discretos, simulación multi-formalismo, procesamiento de
     señales.

- Erwin Meza :: Obtuvo los grados de /ingeniero en sistemas/ (2002) y
                de /maestro en informática/ (2004) por la Universidad
                Industrial de Santander. Docente de las materias de
                sistemas operativos y estructuras de datos desde
                el 2006.  Ha participado en diversos proyectos de
                investigación relacionados con la informática
                educativa.
