#+SETUPFILE: ../setup_notas.org
#+TITLE: Acerca de los autores

- Gunnar Wolf ::

- Esteban Ruiz :: Licenciado en Ciencias de la Computación,
                  Universidad Nacional de Rosario y Técnico
                  Universitario en Computación. Docente desde el 2001
                  a la actualidad en materias como Base de Datos,
                  Comunicaciones, Sistemas Operativos y Arquitectura
                  del Computador. Actualmente realiza también tareas
                  de I+D con software de OCR.

- Federico Bergero :: Obtuvo el título de Licenciado en Ciencias de la
     Computación en el 2008 y de Doctor en Informática en el 2012
     ambos de la Universidad Nacional de Rosario,
     Argentina. Actualmente es becario posdoctoral en CIFASIS-CONICET,
     y también es Profesor de la Universidad Nacional de Rosario en el
     Departamento de Ciencias de la Computación de la FCEIA. Sus
     intereses incluyen sistemas de eventos discretos, simulación
     multi-formalismo, procesamiento de señales.

- Erwin Meza ::
